id = "themeslucasarielaguirre"
name = "ThemesLucasArielAguirre"
version = "0.0.1"
schema_version = 1
authors = ["Lucas Ariel Aguirre"]
description = "Theme created temporarily"
repository = "https://github.com/LucasArielAguirre/ThemeDarKViolet"
